definitions:
  memorize_internal_service_authentication.LoginUserRequest:
    properties:
      password:
        maxLength: 70
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - password
    - username
    type: object
  memorize_internal_service_authentication.RegisterUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 70
        type: string
    required:
    - email
    - password
    type: object
  memorize_internal_service_authentication_user.CreateUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 70
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - username
    type: object
  memorize_internal_service_authentication_user.UpdateUserRequest:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 70
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - username
    type: object
  memorize_internal_service_question.CreateQuestionRequest:
    properties:
      answer_text:
        maxLength: 1000
        type: string
      question_text:
        maxLength: 100
        type: string
      title:
        maxLength: 50
        type: string
    required:
    - answer_text
    - question_text
    type: object
  memorize_internal_service_question.UpdateQuestionRequest:
    properties:
      answer_text:
        maxLength: 1000
        type: string
      question_text:
        maxLength: 100
        type: string
      title:
        maxLength: 50
        type: string
    required:
    - answer_text
    - question_text
    type: object
externalDocs:
  description: Open Swagger UI
  url: http://localhost:8000/swagger/index.html
host: localhost:8000
info:
  contact: {}
  title: Memorize API
  version: "1.0"
paths:
  /admin/question:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      responses: {}
      tags:
      - Question
    post:
      parameters:
      - description: entity to create
        in: body
        name: Question
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_question.CreateQuestionRequest'
      responses: {}
      tags:
      - Question
  /admin/question/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      tags:
      - Question
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      tags:
      - Question
    put:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: entity to update
        in: body
        name: Question
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_question.UpdateQuestionRequest'
      responses: {}
      tags:
      - Question
  /admin/users:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      responses: {}
      tags:
      - Users
    post:
      parameters:
      - description: entity to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_authentication_user.CreateUserRequest'
      responses: {}
      tags:
      - Users
  /admin/users/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      tags:
      - Users
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      tags:
      - Users
    put:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: entity to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_authentication_user.UpdateUserRequest'
      responses: {}
      tags:
      - Users
  /auth/login:
    post:
      parameters:
      - description: login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_authentication.LoginUserRequest'
      responses: {}
      tags:
      - Authentication
  /auth/register:
    post:
      parameters:
      - description: register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/memorize_internal_service_authentication.RegisterUserRequest'
      responses: {}
      tags:
      - Authentication
swagger: "2.0"
