package router

import (
	"log"
	"memorize/config"
	authHandler "memorize/internal/handler/authentication"
	userHandler "memorize/internal/handler/authentication/user"
	"memorize/internal/middleware"
	"memorize/internal/model"
	authenticationModel "memorize/internal/model/authentication"
	"memorize/internal/repository"
	"memorize/internal/service/authentication"
	userService "memorize/internal/service/authentication/user"
	"memorize/pkg/database"
	"memorize/pkg/security/jwt"
	"memorize/pkg/validator"

	_ "memorize/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/fx"
)

func NewRouter(userHandler *userHandler.UserHandler,
	authHandler *authHandler.AuthHandler,
	authMiddleware *middleware.AuthMiddleware,
) *gin.Engine {
	router := gin.Default()

	unAuthorizedRoutes := router.Group("")
	_ = authHandler.SetRoutes(unAuthorizedRoutes)

	// Question routes
	// questionRoutes := router.Group("/questions")
	// {
	// 	questionRoutes.GET("", questionController.ListQuestions)
	// 	questionRoutes.GET("/:id", questionController.GetQuestionByID)
	// 	questionRoutes.POST("", questionController.CreateQuestion)
	// 	questionRoutes.PUT("/:id", questionController.UpdateQuestion)
	// 	questionRoutes.DELETE("/:id", questionController.DeleteQuestion)
	// }

	authorizedRoutes := router.Group("")
	authorizedRoutes.Use(authMiddleware.Handle())
	{
		adminAuthorizedRoutes := authorizedRoutes.Group("/admin")
		{
			_ = userHandler.SetRoutes(adminAuthorizedRoutes)
		}
	}

	// Swagger endpoint with custom configuration
	router.GET("/swagger/*any",
		ginSwagger.WrapHandler(swaggerFiles.Handler,
			ginSwagger.DefaultModelsExpandDepth(-1),
			ginSwagger.DocExpansion("none")))

	return router
}

var Module = fx.Options(
	fx.Provide(
		config.NewConfig,
		NewRouter,
		jwt.NewJwt,
		middleware.NewAuthMiddleware,

		model.NewListOfDbModels,
		database.NewDatabase,
		validator.NewValidator,

		repository.NewRepository[authenticationModel.User],
		userService.NewUserService,
		userHandler.NewUserHandler,

		authentication.NewAuthService,
		authHandler.NewAuthHandler,

		// repositories.NewRepository[models.Question],
		// questions.NewQuestionService,
		// controllers.NewQuestionController,
	),
	fx.Invoke(runGinServer),
)

func runGinServer(router *gin.Engine) {
	if err := router.Run(":8000"); err != nil {
		log.Fatal(err)
	}
}
